### ISSUE TITLE
Manually setting cur_orthog produces negative entropy

### ISSUE THREAD

**Issue by jerrylvx** [jcmgray/quimb#121]
### What happened?

In the 1d_tebd calculation, the _entropy_ function offers the option to set _cur_orthog_ manually during the update. If I calculate the _magnetization_ at site j before calculating _entropy_ with _cur_orthog_ set to j, then I recover the correct results. However, if I calculate _entropy_ directly with _cur_orthog_ set to j, then I obtain negative entropy values. 

### What did you expect to happen?

I understand that the calculating _magnetization_ somehow adjusts the _cur_orthog_ to j, but nonethelss the entropy should never be negative, instead it should raise an error, regardless of _cur_orthog_ is set automatically or manually.

### Minimal Complete Verifiable Example

```Python
import quimb.tensor as qtn
import numpy as np
import matplotlib.pyplot as plt
import quimb as qu

L = 10
psi1 = qtn.tensor_gen.MPS_neel_state(L)
builder = qtn.SpinHam1D(S=1/2)
builder += 0.5, '+', '-'
builder += 0.5, '-', '+'
H = builder.build_local_ham(L)

tebd = qtn.TEBD(psi1, H)
tebd.split_opts['cutoff'] = 1e-10

ts = np.linspace(0, 20, 101)

mz_t_j = []  
be_t_b = []  

j = 5
for psit in tebd.at_times(ts, tol=1e-3):
    # mz_t_j += [psit.magnetization(j)] uncomment this line gives the correct result
    be_t_b += [psit.entropy(j, cur_orthog=j)] #this line alone gives negative entropy
    # be_t_b += [psit.entropy(j)] or uncomment this line to get the right answer
```

### Environment

1.3.0+393

**Comment by jcmgray** [comment]
I'm not totally sure what the best route here is.

* `cut_orthog` is a efficiency feature, therefore the point is that it doesn't check things and assumes it's being used correctly
* adding a check for negative entropy, doesn't cover the case where its wrong but not negative. Also such checks are nice to avoid as well since behavior conditioned on tensor values (`if x < 0.0: raise ....`) don't play nicely with tracing (e.g. for compiling and autodiffing TN functions)
* checking orthogonality (without tracking it) is relatively expensive

Potential solutions are:
* This could just be made clearer in the docs.
* `quimb` actually now has the infrastructure to track canonicalization automatically on the `Tensor` level with `left_inds`, that would largely negate the need to specify `cur_orthog`.
