### ISSUE TITLE
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

### ISSUE THREAD

**Issue by TanTsiChen** [jcmgray/quimb#19]
Hi, everyone!
I have meet the problem when I tried to import quimb
it returns 
`Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!`
I have tried to reinstall quimb, but nothing change.

**Comment by jcmgray** [comment]
Not much to go on here but I'm pretty sure this is not an issue related to ``quimb`` (which is pure python - doesn't itself do any compiling/linking). Maybe try importing the main required libraries separately and seeing which errors:
```python
import numpy
import scipy
import numba
import cytoolz
```
I also strongly recommend using [conda](https://docs.conda.io/en/latest/miniconda.html) as your python environement if you are not already to install as many packages as possible. Both because it will satisfy all sorts of library requirements (and resolve these kind of errors) and for performance reasons.

**Comment by TanTsiChen** [comment]
Thx for your reply!
The problem is that these modules work very well, I'm not sure what's the point.
BTW, I'm using conda, and the quimb is installed by pip which is installed by conda. Also, even when I download the source code, and using `export PYTHONPATH=[path of quimb]`, it also returns the same error.

**Comment by jcmgray** [comment]
Intriguing! Can you try installing numba=0.39? I remember there was some issues beginning with numba 0.40.

**Comment by TanTsiChen** [comment]
I have tried to install numba=0.39, but it doesn't help.

**Comment by jcmgray** [comment]
Hmm, not sure what else to suggest other than reinstalling your conda environment! Before that you might try uninstalling ``quimb`` and ``numba`` (which I suspect as the origin of the error), and making sure that no cruft / cache files have been left in the ``site-packages`` folder then reinstalling. Often when I have hard to pin down errors it's due to leftover stuff in this folder messing with import versions.

**Comment by TanTsiChen** [comment]
I have tried to install quimb on my Macbook (the error was found on my desktop in office), and it runs well :)

**Comment by TanTsiChen** [comment]
problem solved by reinstalling conda and pip environment.
